main:
  push:
    - services:
        - docker

      env:
        IMAGE_NAME: ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}

      stages:
        - name: Build Docker image
          script: |
            docker build \
              -t ${IMAGE_NAME}:latest \
              -t ${IMAGE_NAME}:${CNB_COMMIT_SHORT} \
              .

        - name: Push Docker image
          script: |
            docker push ${IMAGE_NAME}:latest
            docker push ${IMAGE_NAME}:${CNB_COMMIT_SHORT}
