import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import type { Project,Tag } from '@zhoubao/shared';
import { Archive,FolderKanban,Plus,RotateCcw,Tag as TagIcon,Trash2 } from 'lucide-react';
import { useState } from 'react';
import { api } from '../api';
import { EmptyState,Loading,Modal } from '../components';

const palette=['#456990','#4F7C68','#B06C49','#8069A8','#C48B2B','#4D8B8B'];
export function ProjectsPage(){const qc=useQueryClient();const [projectOpen,setProjectOpen]=useState(false);const [tagOpen,setTagOpen]=useState(false);const [name,setName]=useState('');const [color,setColor]=useState(palette[0]);
  const projects=useQuery({queryKey:['projects'],queryFn:()=>api<{projects:Project[]}>('/api/projects')});const tags=useQuery({queryKey:['tags'],queryFn:()=>api<{tags:Tag[]}>('/api/tags')});
  const createProject=useMutation({mutationFn:()=>api('/api/projects',{method:'POST',body:JSON.stringify({name,color})}),onSuccess:()=>{setProjectOpen(false);setName('');qc.invalidateQueries({queryKey:['projects']});}});const createTag=useMutation({mutationFn:()=>api('/api/tags',{method:'POST',body:JSON.stringify({name,color})}),onSuccess:()=>{setTagOpen(false);setName('');qc.invalidateQueries({queryKey:['tags']});}});
  const changeProject=useMutation({mutationFn:({id,body}:{id:string;body:any})=>api(`/api/projects/${id}`,{method:'PATCH',body:JSON.stringify(body)}),onSuccess:()=>qc.invalidateQueries({queryKey:['projects']})});
  if(projects.isLoading||tags.isLoading)return <div className="page"><Loading/></div>;
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">Structure</span><h1>项目与标签</h1><p>用项目划分工作边界，用标签保留跨项目的线索。</p></div><button className="button" onClick={()=>{setName('');setProjectOpen(true);}}><Plus size={17}/>新建项目</button></div>
    <div className="management-grid"><section className="management-panel"><div className="panel-heading"><h2>项目</h2><span>{projects.data!.projects.filter(p=>!p.archivedAt).length} 个进行中</span></div>{projects.data!.projects.length?<div className="project-list">{projects.data!.projects.map(project=><div className={`project-row ${project.archivedAt?'archived':''}`} key={project.id}><span className="project-swatch" style={{background:project.color}}/><div><strong>{project.name}</strong><span>{project.archivedAt?'已归档':'进行中'}</span></div><button className="icon-button" title={project.archivedAt?'恢复':'归档'} onClick={()=>changeProject.mutate({id:project.id,body:{archived:!project.archivedAt}})}>{project.archivedAt?<RotateCcw size={17}/>:<Archive size={17}/>}</button></div>)}</div>:<EmptyState icon={<FolderKanban/>} heading="还没有项目" body="建立第一个项目，让每条周报都有清晰归属。"/>}</section>
      <section className="management-panel"><div className="panel-heading"><h2>标签</h2><button className="button ghost" onClick={()=>{setName('');setTagOpen(true);}}><Plus size={16}/>添加标签</button></div>{tags.data!.tags.length?<div className="tag-cloud">{tags.data!.tags.map(tag=><span className="large-tag" key={tag.id}><i style={{background:tag.color}}/>{tag.name}</span>)}</div>:<EmptyState icon={<TagIcon/>} heading="还没有标签" body="标签适合标记技术领域、工作性质或状态。"/>}</section></div>
    <CreateModal open={projectOpen} onOpenChange={setProjectOpen} title="新建项目" name={name} setName={setName} color={color} setColor={setColor} onSubmit={()=>createProject.mutate()} pending={createProject.isPending}/><CreateModal open={tagOpen} onOpenChange={setTagOpen} title="添加标签" name={name} setName={setName} color={color} setColor={setColor} onSubmit={()=>createTag.mutate()} pending={createTag.isPending}/>
  </div>;
}
function CreateModal({open,onOpenChange,title,name,setName,color,setColor,onSubmit,pending}:{open:boolean;onOpenChange:(o:boolean)=>void;title:string;name:string;setName:(s:string)=>void;color:string;setColor:(s:string)=>void;onSubmit:()=>void;pending:boolean}){return <Modal open={open} onOpenChange={onOpenChange} title={title}><form className="dialog-form" onSubmit={e=>{e.preventDefault();onSubmit();}}><label>名称<input autoFocus value={name} onChange={e=>setName(e.target.value)} required maxLength={80}/></label><fieldset><legend>颜色</legend><div className="color-picker">{palette.map(value=><button type="button" key={value} className={color===value?'selected':''} style={{background:value}} onClick={()=>setColor(value)} aria-label={`选择颜色 ${value}`}/>)}</div></fieldset><div className="dialog-actions"><button type="button" className="button secondary" onClick={()=>onOpenChange(false)}>取消</button><button className="button" disabled={pending}>{pending?'创建中…':'创建'}</button></div></form></Modal>;}
