import { useMutation,useQuery,useQueryClient } from '@tanstack/react-query';
import { CheckCircle2,ExternalLink,Link2,ShieldCheck,Unlink } from 'lucide-react';
import { api } from '../api';
import { Loading } from '../components';

const names:Record<string,string>={google:'Google',microsoft:'Microsoft',github:'GitHub',apple:'Apple'};
export function SettingsPage({user}:{user:{displayName:string;email:string|null}}){const qc=useQueryClient();const accounts=useQuery({queryKey:['accounts'],queryFn:()=>api<{accounts:Array<{id:string;provider:string;email:string|null;displayName:string|null;lastLoginAt:string|null}>}>('/api/auth/accounts')});const providers=useQuery({queryKey:['providers'],queryFn:()=>api<{providers:Array<{provider:string;enabled:boolean}>}>('/api/auth/providers')});const unlink=useMutation({mutationFn:(provider:string)=>api(`/api/auth/accounts/${provider}`,{method:'DELETE'}),onSuccess:()=>qc.invalidateQueries({queryKey:['accounts']})});if(accounts.isLoading||providers.isLoading)return <div className="page"><Loading/></div>;
  return <div className="page"><div className="page-heading"><div><span className="eyebrow">Preferences</span><h1>设置</h1><p>管理身份、安全与本地数据状态。</p></div></div><div className="settings-stack"><section className="settings-card"><div className="settings-icon"><ShieldCheck/></div><div className="settings-body"><h2>个人空间</h2><p>当前空间所有者为 <strong>{user.displayName}</strong>{user.email&&<> · {user.email}</>}。公网注册已关闭，只有已绑定身份可以登录。</p><div className="security-note"><CheckCircle2 size={16}/>Session 仅使用安全 HttpOnly Cookie，身份不会按邮箱自动合并。</div></div></section><section className="settings-card vertical"><div className="panel-heading"><div><h2>登录方式</h2><p>先登录当前账号，再绑定其他身份。</p></div></div><div className="account-list">{providers.data!.providers.map(provider=>{const account=accounts.data!.accounts.find(a=>a.provider===provider.provider);return <div className="account-row" key={provider.provider}><span className={`provider-icon ${provider.provider}`}>{provider.provider==='google'?'G':provider.provider==='microsoft'?'⊞':provider.provider==='github'?'GH':'●'}</span><div><strong>{names[provider.provider]}</strong><span>{account?account.email??account.displayName??'已绑定':provider.enabled?'尚未绑定':'尚未配置'}</span></div>{account?<button className="button secondary danger-text" disabled={accounts.data!.accounts.length===1||unlink.isPending} onClick={()=>unlink.mutate(provider.provider)}><Unlink size={15}/>解绑</button>:provider.enabled?<a className="button secondary" href={`/api/auth/accounts/${provider.provider}/link`}><Link2 size={15}/>绑定</a>:<span className="status-badge">不可用</span>}</div>;})}</div></section><section className="settings-card"><div className="settings-icon"><ExternalLink/></div><div className="settings-body"><h2>节假日与备份</h2><p>法定节假日由年度 JSON 导入；SQLite 每日 03:00 在线备份，自动保留 30 天。</p><code>pnpm holiday:import 2026</code><code>pnpm db:backup</code></div></section></div></div>;
}
